name: .NET Core

on:
  push:
  pull_request:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Build
      run: dotnet build Dandomain/DandomainApi.csproj --configuration Release
    
        # Publish
    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Dandomain/DandomainApi.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # VERSION_STATIC: Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.nuget_token}} # nuget.org API key
          PACKAGE_NAME: DandomainApi
